--- !ruby/object:Game
player: !ruby/object:Player
  guesses:
  - a
  - "y"
word: brilliant
guesses: 1
status: ______a__

--- !ruby/object:Game
player: !ruby/object:Player
  guesses:
  - a
  - "y"
  - b
word: brilliant
guesses: 1
status: b_____a__

--- !ruby/object:Game
player: !ruby/object:Player
  guesses:
  - i
  - e
word: globe
guesses: 1
status: ____e

