--- !ruby/object:Game
player: !ruby/object:Player
  guesses: []
word: ireland
guesses: 0
status: _______

--- !ruby/object:Game
player: !ruby/object:Player
  guesses: []
word: changed
guesses: 0
status: _______

